Client Barebones and Login GUI
Sepulchre49/instant-messenger pull request #6
Opened 2024-04-16 12:50 UTC by cc-noppy

2024-04-16 18:31 UTC, Sepulchre49 requested changes

2024-04-16 18:31 UTC, Sepulchre49 commented on src/client/Client.java
Please fix indentation, set to 4 spaces.

2024-04-16 21:43 UTC, cc-noppy commented
Cleaned up indentations. Let me know if there's any more discrepancies and I'll hop on in ASAP.

2024-04-17 02:37 UTC, Sepulchre49 approved these changes

2024-04-17 02:38 UTC, merged